apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: console-deployments-reader
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: console-deployments-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: console-sa
    namespace: default
roleRef:
  kind: Role
  name: console-deployments-reader
  apiGroup: rbac.authorization.k8s.io
